### ISSUE TITLE
AttributeError: 'fbRssAdMonitor' object has no attribute 'logger'

### ISSUE THREAD

**Issue by SugarRayLua** [regek/facebook-marketplace-rss#2]
Hi-- your Facebook Marketplace program looks like it will be very helpful!

However, even though I think I installed it correctly, I'm getting the following attribute error when I'm trying to set up the server:

```
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ python3
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ python fb_ad_monitor.py
Traceback (most recent call last):
  File "/home/mikes/facebook-marketplace-rss/fb_ad_monitor.py", line 145, in load_from_json
    self.refersh_interval_minutes = data['refersh_interval_minutes']
                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'refersh_interval_minutes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikes/facebook-marketplace-rss/fb_ad_monitor.py", line 393, in <module>
    monitor = fbRssAdMonitor(json_file=config_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mikes/facebook-marketplace-rss/fb_ad_monitor.py", line 45, in __init__
    self.load_from_json(json_file)
  File "/home/mikes/facebook-marketplace-rss/fb_ad_monitor.py", line 150, in load_from_json
    self.logger.error(f"Error loading filters from JSON: {e}")
    ^^^^^^^^^^^
AttributeError: 'fbRssAdMonitor' object has no attribute 'logger'
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ ls
'=3.10.4'      config.sample.json   fb-rss-feed.db   lib       pyvenv.cfg         venv
 bin           Dockerfile           include          lib64     README.md
 config.json   fb_ad_monitor.py     init_db.py       LICENSE   requirements.txt
```

Any suggestions?

I'm on a Ubuntu Noble derivative, AMD x86_64 and t=using your example json
file as the config.json file

Thanks!

**Comment by regek** [comment]
seems like an issue with `config.json`
check if this key is correct 'refersh_interval_minutes' in the `config.json`

**Comment by SugarRayLua** [comment]
Thanks, @regek.

This is my config.json (copied from example):
```
{
    "server_ip": "0.0.0.0",
    "server_port": "5000", 
    "currency": "$",
    "refresh_interval_minutes": 15,
    "log_filename": "fb-rssfeed.log",
    "url_filters": {
        "https://www.facebook.com/marketplace/page1": {
            "level1": ["tv"],
            "level2": ["smart"],
            "level3": ["55\"", "55 inch"]
        },
        "https://www.facebook.com/marketplace/page2": {
            "level1": ["dishwasher"],
            "level2": ["kitchenaid", "samsung"]
        },
        "https://www.facebook.com/marketplace/page2": {}
    }
}
```
refresh_interval_minutes seems to present and set to value 15

**Comment by regek** [comment]
pull the latest, it should be fixed

**Comment by SugarRayLua** [comment]
Thanks, @regek 

I pulled the latest, and the server does run now without that error.

However, I think I might be still missing a step. I couldn't get any result when I tried using the config.example.json as my config.json, and then to better troubleshoot changed the config.json to this simple file:

```{
    "server_ip": "0.0.0.0",
    "server_port": "5000", 
    "currency": "$",
    "refresh_interval_minutes": 15,
    "log_filename": "fb-rssfeed.log",
    "url_filters": {
        "https://www.facebook.com/marketplace/": {
            "level1": ["tv"],
            "level2": ["smart"],
            "level3": ["55 inch"]
        }
    }
}
```
I then tried to point my browser to the localhost address specified in the message I got below as to the access I assume I could access the results at (http://127.0.0.1:5000/) and got a 404 error as below:
```
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ python fb_ad_monitor.py
 * Serving Flask app 'fb_ad_monitor'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [04/Dec/2024 18:48:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [04/Dec/2024 18:48:10] "GET /favicon.ico HTTP/1.1" 404 -
^CTraceback (most recent call
```
Am I perhaps missing a step or did I do anything incorrectly in the above setup?

Thanks!

**Comment by regek** [comment]
feed url` http://server_ip:server_port/rss`

**Comment by SugarRayLua** [comment]
Thanks, @regek. I'm think I'm getting closer but still not there. 

Here is my test config.json file:
```
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ cat config.json
{
    "server_ip": "0.0.0.0",
    "server_port": "5000", 
    "currency": "$",
    "refresh_interval_minutes": 15,
    "log_filename": "fb-rssfeed.log",
    "url_filters": {
        "https://www.facebook.com/marketplace/": {
            "level1": ["tv"],
            "level2": ["smart"],
            "level3": ["55 inch"]
        }
    }
}
```
And here is my initial startup commands:
```
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ python3 init_db.py
Database initialized.
(venv) mikes@tuxedo-os:~/facebook-marketplace-rss$ python3 fb_ad_monitor.py
 * Serving Flask app 'fb_ad_monitor'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.218:5000
Press CTRL+C to quit
127.0.0.1 - - [06/Dec/2024 19:01:58] "GET /rss HTTP/1.1" 200 -
127.0.0.1 - - [06/Dec/2024 19:01:58] "GET /favicon.ico HTTP/1.1" 404 -
```
Which to indicate the server and request begin to work but cannot retrieve the favicon

Then I put in the URL based on the syntax you suggested above:
```
http://127.0.0.1:5000/rss
```
And get this xml result:
```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"><channel><title>Facebook Marketplace Ad Feed</title><link>http://monitor.local/rss</link><description>An RSS feed to monitor new ads on Facebook Marketplace</description><lastBuildDate>Sat, 07 Dec 2024 03:01:58 GMT</lastBuildDate><generator>PyRSS2Gen-1.1.0</generator><docs>http://blogs.law.harvard.edu/tech/rss</docs></channel></rss>
```

**Comment by wheat4714** [comment]
I was using "refersh_interval_minutes" in my config file. The update broke my server and I had an extended period of downtime.

Please be mindful of breaking changes in the future.

Thank you.
